spring.application.name=bus-ticket-booking
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Common JPA
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=BusTicketBookingSecretKeyForJWTAuthenticationMustBe256BitsLongForHS256Algorithm2024
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.busticket=DEBUG

# Custom configs
seat.lock.expiry.minutes=5
schedule.days.ahead=7